name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: stable

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: jarvis-apk
          path: ${{ steps.buildozer.outputs.filename }}
